// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogList: typeof import('./src/components/common/blogList.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Date: typeof import('./src/components/date/date.vue')['default']
    Edit: typeof import('./src/components/edit.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Fc: typeof import('./src/components/games/fc/fc.vue')['default']
    Footer: typeof import('./src/components/common/footer.vue')['default']
    Header: typeof import('./src/components/common/header.vue')['default']
    Markdown: typeof import('./src/components/Markdown/src/Markdown.vue')['default']
    MarkdownViewer: typeof import('./src/components/Markdown/src/MarkdownViewer.vue')['default']
    Menu: typeof import('./src/components/common/menu.vue')['default']
    Music: typeof import('./src/components/Video/music.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Simditor: typeof import('./src/components/simditor.vue')['default']
    Test: typeof import('./src/components/games/fc/test.vue')['default']
    VideoPlayer: typeof import('./src/components/Video/VideoPlayer.vue')['default']
  }
}
