// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    Edit: typeof import('./src/components/edit.vue')['default']
    Fc: typeof import('./src/components/games/fc/fc.vue')['default']
    Header: typeof import('./src/components/common/header.vue')['default']
    Markdown: typeof import('./src/components/Markdown/src/Markdown.vue')['default']
    MarkdownViewer: typeof import('./src/components/Markdown/src/MarkdownViewer.vue')['default']
    Menu: typeof import('./src/components/common/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Simditor: typeof import('./src/components/simditor.vue')['default']
    Test: typeof import('./src/components/games/fc/test.vue')['default']
    Undefined: typeof import('./src/components/index.vue')['default']
  }
}
